language: julia
julia:
      - release
      - nightly
before_script:
  - julia -e 'Pkg.clone("git@github.com:grero/Entropies.jl")'
after_success:
      - julia -e 'cd(Pkg.dir("DirectedInformation")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
